language: python
dist: xenial

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - sudo apt-get install -y python-tk
  - sudo apt-get install -y python3-tk
install:
  - pip install -e ".[test]"
script:
  - python -m unittest
after_success:
  - coverage run --source=pysankey --omit=pysankey/tests/* -m unittest
  - coverage html
  - coveralls
